[theme]
primaryColor = "#E30613"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A1A"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
